# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/sawtooth_block_info/protobuf/signerMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='python/sawtooth_block_info/protobuf/signerMessages.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n8python/sawtooth_block_info/protobuf/signerMessages.proto\x12\x02pb\"\x9c\x01\n\x0fProtocolMessage\x12&\n\x04type\x18\x01 \x01(\x0e\x32\x18.pb.ProtocolMessage.Type\x12\x16\n\x0e\x63orrelation_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\x0c\"8\n\x04Type\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x10\n\x0cSIGN_REQUEST\x10\x64\x12\x11\n\rSIGN_RESPONSE\x10\x65\"P\n\x11\x43lientSignMessage\x12\x0c\n\x04UUID\x18\x01 \x01(\t\x12\x1c\n\x14SmartContractAddress\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\x0c\"7\n\x12\x43lientSignResponse\x12\x0e\n\x06scheme\x18\x01 \x01(\t\x12\x11\n\tsignature\x18\x02 \x01(\x0c\"/\n\x0cSignResponse\x12\x0c\n\x04UUID\x18\x01 \x01(\t\x12\x11\n\tsignature\x18\x02 \x01(\x0c\"\\\n\x13\x43lientVerifyMessage\x12\x0e\n\x06Scheme\x18\x01 \x01(\t\x12\x12\n\npublic_key\x18\x02 \x01(\x0c\x12\x0e\n\x06\x64igest\x18\x03 \x01(\x0c\x12\x11\n\tsignature\x18\x04 \x01(\x0c\"x\n\x14\x43lientVerifyResponse\x12/\n\x06status\x18\x01 \x01(\x0e\x32\x1f.pb.ClientVerifyResponse.Status\"/\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x0b\n\x07INVALID\x10\x02\"\xc2\x01\n\x12MembershipResponse\x12-\n\x06status\x18\x01 \x01(\x0e\x32\x1d.pb.MembershipResponse.Status\x12*\n\x05peers\x18\x02 \x03(\x0b\x32\x1b.pb.MembershipResponse.peer\x1a \n\x04peer\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x03(\t\"/\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x0b\n\x07INVALID\x10\x02\x62\x06proto3')
)



_PROTOCOLMESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='pb.ProtocolMessage.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIGN_REQUEST', index=1, number=100,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIGN_RESPONSE', index=2, number=101,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=165,
  serialized_end=221,
)
_sym_db.RegisterEnumDescriptor(_PROTOCOLMESSAGE_TYPE)

_CLIENTVERIFYRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='pb.ClientVerifyResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS_UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=578,
  serialized_end=625,
)
_sym_db.RegisterEnumDescriptor(_CLIENTVERIFYRESPONSE_STATUS)

_MEMBERSHIPRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='pb.MembershipResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS_UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=578,
  serialized_end=625,
)
_sym_db.RegisterEnumDescriptor(_MEMBERSHIPRESPONSE_STATUS)


_PROTOCOLMESSAGE = _descriptor.Descriptor(
  name='ProtocolMessage',
  full_name='pb.ProtocolMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='pb.ProtocolMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='correlation_id', full_name='pb.ProtocolMessage.correlation_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='pb.ProtocolMessage.content', index=2,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PROTOCOLMESSAGE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=221,
)


_CLIENTSIGNMESSAGE = _descriptor.Descriptor(
  name='ClientSignMessage',
  full_name='pb.ClientSignMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UUID', full_name='pb.ClientSignMessage.UUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SmartContractAddress', full_name='pb.ClientSignMessage.SmartContractAddress', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='pb.ClientSignMessage.content', index=2,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=303,
)


_CLIENTSIGNRESPONSE = _descriptor.Descriptor(
  name='ClientSignResponse',
  full_name='pb.ClientSignResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scheme', full_name='pb.ClientSignResponse.scheme', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='pb.ClientSignResponse.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=360,
)


_SIGNRESPONSE = _descriptor.Descriptor(
  name='SignResponse',
  full_name='pb.SignResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UUID', full_name='pb.SignResponse.UUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='pb.SignResponse.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=409,
)


_CLIENTVERIFYMESSAGE = _descriptor.Descriptor(
  name='ClientVerifyMessage',
  full_name='pb.ClientVerifyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Scheme', full_name='pb.ClientVerifyMessage.Scheme', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='pb.ClientVerifyMessage.public_key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='digest', full_name='pb.ClientVerifyMessage.digest', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='pb.ClientVerifyMessage.signature', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=411,
  serialized_end=503,
)


_CLIENTVERIFYRESPONSE = _descriptor.Descriptor(
  name='ClientVerifyResponse',
  full_name='pb.ClientVerifyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pb.ClientVerifyResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CLIENTVERIFYRESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=505,
  serialized_end=625,
)


_MEMBERSHIPRESPONSE_PEER = _descriptor.Descriptor(
  name='peer',
  full_name='pb.MembershipResponse.peer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pb.MembershipResponse.peer.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addr', full_name='pb.MembershipResponse.peer.addr', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=741,
  serialized_end=773,
)

_MEMBERSHIPRESPONSE = _descriptor.Descriptor(
  name='MembershipResponse',
  full_name='pb.MembershipResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pb.MembershipResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='peers', full_name='pb.MembershipResponse.peers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MEMBERSHIPRESPONSE_PEER, ],
  enum_types=[
    _MEMBERSHIPRESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=628,
  serialized_end=822,
)

_PROTOCOLMESSAGE.fields_by_name['type'].enum_type = _PROTOCOLMESSAGE_TYPE
_PROTOCOLMESSAGE_TYPE.containing_type = _PROTOCOLMESSAGE
_CLIENTVERIFYRESPONSE.fields_by_name['status'].enum_type = _CLIENTVERIFYRESPONSE_STATUS
_CLIENTVERIFYRESPONSE_STATUS.containing_type = _CLIENTVERIFYRESPONSE
_MEMBERSHIPRESPONSE_PEER.containing_type = _MEMBERSHIPRESPONSE
_MEMBERSHIPRESPONSE.fields_by_name['status'].enum_type = _MEMBERSHIPRESPONSE_STATUS
_MEMBERSHIPRESPONSE.fields_by_name['peers'].message_type = _MEMBERSHIPRESPONSE_PEER
_MEMBERSHIPRESPONSE_STATUS.containing_type = _MEMBERSHIPRESPONSE
DESCRIPTOR.message_types_by_name['ProtocolMessage'] = _PROTOCOLMESSAGE
DESCRIPTOR.message_types_by_name['ClientSignMessage'] = _CLIENTSIGNMESSAGE
DESCRIPTOR.message_types_by_name['ClientSignResponse'] = _CLIENTSIGNRESPONSE
DESCRIPTOR.message_types_by_name['SignResponse'] = _SIGNRESPONSE
DESCRIPTOR.message_types_by_name['ClientVerifyMessage'] = _CLIENTVERIFYMESSAGE
DESCRIPTOR.message_types_by_name['ClientVerifyResponse'] = _CLIENTVERIFYRESPONSE
DESCRIPTOR.message_types_by_name['MembershipResponse'] = _MEMBERSHIPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtocolMessage = _reflection.GeneratedProtocolMessageType('ProtocolMessage', (_message.Message,), dict(
  DESCRIPTOR = _PROTOCOLMESSAGE,
  __module__ = 'python.sawtooth_block_info.protobuf.signerMessages_pb2'
  # @@protoc_insertion_point(class_scope:pb.ProtocolMessage)
  ))
_sym_db.RegisterMessage(ProtocolMessage)

ClientSignMessage = _reflection.GeneratedProtocolMessageType('ClientSignMessage', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTSIGNMESSAGE,
  __module__ = 'python.sawtooth_block_info.protobuf.signerMessages_pb2'
  # @@protoc_insertion_point(class_scope:pb.ClientSignMessage)
  ))
_sym_db.RegisterMessage(ClientSignMessage)

ClientSignResponse = _reflection.GeneratedProtocolMessageType('ClientSignResponse', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTSIGNRESPONSE,
  __module__ = 'python.sawtooth_block_info.protobuf.signerMessages_pb2'
  # @@protoc_insertion_point(class_scope:pb.ClientSignResponse)
  ))
_sym_db.RegisterMessage(ClientSignResponse)

SignResponse = _reflection.GeneratedProtocolMessageType('SignResponse', (_message.Message,), dict(
  DESCRIPTOR = _SIGNRESPONSE,
  __module__ = 'python.sawtooth_block_info.protobuf.signerMessages_pb2'
  # @@protoc_insertion_point(class_scope:pb.SignResponse)
  ))
_sym_db.RegisterMessage(SignResponse)

ClientVerifyMessage = _reflection.GeneratedProtocolMessageType('ClientVerifyMessage', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTVERIFYMESSAGE,
  __module__ = 'python.sawtooth_block_info.protobuf.signerMessages_pb2'
  # @@protoc_insertion_point(class_scope:pb.ClientVerifyMessage)
  ))
_sym_db.RegisterMessage(ClientVerifyMessage)

ClientVerifyResponse = _reflection.GeneratedProtocolMessageType('ClientVerifyResponse', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTVERIFYRESPONSE,
  __module__ = 'python.sawtooth_block_info.protobuf.signerMessages_pb2'
  # @@protoc_insertion_point(class_scope:pb.ClientVerifyResponse)
  ))
_sym_db.RegisterMessage(ClientVerifyResponse)

MembershipResponse = _reflection.GeneratedProtocolMessageType('MembershipResponse', (_message.Message,), dict(

  peer = _reflection.GeneratedProtocolMessageType('peer', (_message.Message,), dict(
    DESCRIPTOR = _MEMBERSHIPRESPONSE_PEER,
    __module__ = 'python.sawtooth_block_info.protobuf.signerMessages_pb2'
    # @@protoc_insertion_point(class_scope:pb.MembershipResponse.peer)
    ))
  ,
  DESCRIPTOR = _MEMBERSHIPRESPONSE,
  __module__ = 'python.sawtooth_block_info.protobuf.signerMessages_pb2'
  # @@protoc_insertion_point(class_scope:pb.MembershipResponse)
  ))
_sym_db.RegisterMessage(MembershipResponse)
_sym_db.RegisterMessage(MembershipResponse.peer)


# @@protoc_insertion_point(module_scope)
