#!/bin/bash


docker-compose -f docker-compose-installed-partial.yaml build

# Push container Azure Container Registry
docker push ghcr.io/jffp113/sawtooth-validator:latest
docker push ghcr.io/jffp113/sawtooth-rest-api:latest

